# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40fcd6a16ae97ecb488153e4157e870692be420d326655d1917d9e82bf39065cfeae0ea299aa24515b81a8d4173c74d194b9a8f65217e84fb463579c10f3e00f

test:
  secret_key_base: 799ec687138b4d8aafff0321414752f928bcf23ef18b37873a4531acdb7f5252c3e7e8e43e69c24142292781c4ba103b98b7af72de0c1506c650d50857099fb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
